# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('no_of_vacancies', models.CharField(max_length=100)),
                ('last_date', models.DateTimeField(db_index=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
