# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='last_date',
            field=models.DateField(db_index=True),
        ),
    ]
