# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='grade_t',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='Education',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Experience',
            field=models.TextField(default='not yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Delhi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
