# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180214_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Work',
            field=models.TextField(default='nk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='about_yourself',
            field=models.TextField(default='m,m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='kl'),
            preserve_default=False,
        ),
    ]
