# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180214_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Work',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_yourself',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='static\x07bc1.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
