# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180217_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='password',
        ),
    ]
