# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 02:49
from __future__ import unicode_literals

from django.db import migrations
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_managers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='password',
            field=register.models.PasswordModelField(default='qwert', max_length=200),
            preserve_default=False,
        ),
    ]
