# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20180218_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
